# Generated by Django 5.1.6 on 2025-02-11 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 11, 16, 8, 36, 251762)),
        ),
    ]
